version: '3'

volumes:
    node_modules:
services:
    dev-application:
        build:
            context: .
            dockerfile: Dockerfile.dev
        container_name: nuxt-dev
        ports:
            - '3000:3000'
            - '24678:24678'
        volumes:
            - .:/src
            - node_modules:/node_modules
